### ISSUE TITLE
list of existing C and C++ libraries that can be handled?

### ISSUE THREAD

**Issue by timotheecour** [genotrance/nimterop#1]
Very interested in this repo; is there a list of existing C and C++ libraries that can be handled? (besides https://github.com/genotrance/nimterop/blob/master/tests/include/test.h)
"currently 0" is ok as an answer if that's the case, I understand it's an early release

**Comment by genotrance** [comment]
I was testing this with the tree-sitter runtime.h itself and it worked pretty well, but that was only #defines, structs and enums, not procs. It's worth trying with simpler libs so that issues can be identified.

I will be testing with libs as I go but eager on hearing from the community as well.

**Comment by genotrance** [comment]
Have been tracking the supported features in the README - will expand as nimterop expands. Any tree-sitter limitations will be reported upstream - they have been quite responsive.
