### ISSUE TITLE
changing global from include to import includes treesitter in every wrapper

### ISSUE THREAD

**Issue by timotheecour** [genotrance/nimterop#104]
https://gitter.im/nimgen/Lobby?at=5c530ca79221b9382df134bd

changing global from include to import includes treesitter in every wrapper
because the when not declared(CIMPORT) doesn't work

**Comment by genotrance** [comment]
This is already fixed in https://github.com/genotrance/nimterop/commit/ada2ac0244b9ca8f9e365c31444cbf61cc372788
