### ISSUE TITLE
more feedback

### ISSUE THREAD

**Issue by timotheecour** [genotrance/nimterop#20]
- [x] is that a bug?
`if gStateRT.mode.len != 0: gStateRT.mode = “cpp"`

- [ ] globals.nim:
State* = object
=> State* = ref object

- [ ] this change:
node.children.len
=>
tsNodeNamedChildCount()
seems works; can we add back a nicer API (where one can use `len`) ?

- [x] README needs to be updated to reflect `Move AST to Nim processing into toast` commit

- [x] s/staticExec/gorgeEx/g (staticExec less safe, ignores exit code)

**Comment by genotrance** [comment]
For 3, would be cool to add an idiomatic Nim layer on top of tree-sitter that we can simply use.

For 5, there's execAction() in git.nim which can be leveraged.
