### ISSUE TITLE
no ERROR generated in AST, but should be

### ISSUE THREAD

**Issue by timotheecour** [genotrance/nimterop#25]
```h
// uncomment this and no ERROR will be generated
// #whateverstuff TEST_INT 512

asdfasdf
```

before uncommenting
```
(translation_unit 0 45
 (comment 0 3)
 (comment 4 34)
 (ERROR 36 44
  (identifier 36 44)
 )
)
```

after uncommenting

```
(translation_unit 0 42
 (comment 0 3)
 (preproc_call 4 32
  (preproc_directive 4 18)
  (preproc_arg 18 31)
 )
 (expression_statement 33 41
  (identifier 33 41)
 )
)

```

cmd:
./toast --past --source:/Users/timothee/git_clone/nim/nimterop/tests/include/test_bug2.h

**Comment by genotrance** [comment]
This really should go in the [tree-sitter-cpp](https://github.com/tree-sitter/tree-sitter-cpp) repo.

**Comment by timotheecour** [comment]
do you know any quick cmd line to test tree-sitter-cpp directly so I/you/anyone can report a standalone bug in their repo?

**Comment by genotrance** [comment]
Yes, you can just use the `-a | --past` flag and it will spit out the Lisp tree for a given file. If you want to avoid preprocessor, simply use the `-p` flag as well. The output is pretty similar to the output they generate with their API itself.

tree-sitter folks haven't been as responsive to the issues I've submitted in the last month though.

**Comment by genotrance** [comment]
Need to open against tree-sitter.
