### ISSUE TITLE
[minor] `nimble test` fails due to dirty nimcache, -f needed sometimes

### ISSUE THREAD

**Issue by timotheecour** [genotrance/nimterop#29]
git rev-parse HEAD
1e086d59595c24ee8ec3f1dcc02b55d97fe9e2ec

nimble installWithDeps
nimble test

```
Hint:  [Link]
Undefined symbols for architecture x86_64:
  "__test_call_param_", referenced from:
      _NimMainModule in nimterop_tnimterop_c.c.o
  "_test_call_param2", referenced from:
      _NimMainModule in nimterop_tnimterop_c.c.o
  "_test_call_param3", referenced from:
      _NimMainModule in nimterop_tnimterop_c.c.o
  "_test_call_param4", referenced from:
      _NimMainModule in nimterop_tnimterop_c.c.o
  "_test_call_param5", referenced from:
      _NimMainModule in nimterop_tnimterop_c.c.o
  "_test_call_param6", referenced from:
      _NimMainModule in nimterop_tnimterop_c.c.o
  "_test_call_param7", referenced from:
      _NimMainModule in nimterop_tnimterop_c.c.o
  "_test_call_param8", referenced from:
      _NimMainModule in nimterop_tnimterop_c.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed: 'g++   -o /Users/timothee/git_clone/nim/nimterop/tests/tnimterop_c  /Users/timothee/.cache/nim/tnimterop_c_d/runtime.c.o /Users/timothee/.cache/ni...
```

EDIT: using `-f` to force rebuild worked:
```
nim c -r -f tests/tnimterop_c.nim
```
(so may be hard to reproduce...)

is that a nim bug where nim should recompile because something changed, but didn't recompile?

**Comment by genotrance** [comment]
I've seen this happen quite a few times in many projects, I've usually deleted the nimcache and tried again. It's a Nim issue in my mind.

@Araq, can you please comment on this?

**Comment by Araq** [comment]
Nim caches object files from ``.compile`` via a checksum that ignore the C's file dependencies. Solution: Don't develop C code with Nim.

**Comment by genotrance** [comment]
Cannot do much when you are wrapping C libraries :D

Closing since this is beyond nimterop.

**Comment by timotheecour** [comment]
* just filed https://github.com/nim-lang/Nim/issues/10441 which explains the problem and has a proposal for a simple solution
* also found a minimal test case that I turned into a PR, see https://github.com/nim-lang/Nim/pull/10442
