### ISSUE TITLE
va_list support

### ISSUE THREAD

**Issue by zestyr** [genotrance/nimterop#36]
ImageMagick uses the type in these two functions:
```C
ThrowMagickExceptionList(ExceptionInfo *, const char *, const char *,
  const size_t, const ExceptionType, const char *, const char *, va_list),

LogMagickEventList(const LogEventType, const char *, const char *, const size_t,
  const char *, va_list);
```

First one in `exception.c` uses the value here (`operands` is the `va_list`):
`n = vsprintf(reason+length, format, operands);`

Currently nimterop just keeps the `va_list` type, but it's undeclared in Nim.

Maybe something like 
```nim
type va_list {.importc: "va_list", header:"<stdarg.h>".} = object
```

**Comment by genotrance** [comment]
cc @irskep

I can add the va_list declaration if I detect it in the code being parsed but if you do cImport twice and each one detects va_list, you will run into duplicates.

Instead, I am thinking of adding it to cimport itself so when you import it, va_list will get declared once and for all.

I'm thinking this is also a better way to handle time_t.

Feedback appreciated.
