### ISSUE TITLE
toast hangs on readlines 'rltypes.h

### ISSUE THREAD

**Issue by zevv** [genotrance/nimterop#49]
This is the offending line, if I put that on its on in a file, toast will eat my CPU and never finish:

```
cat > t.h <<EOT
typedef int rl_command_func_t PARAMS((int, int));
EOT
./toast -np r.h 
```

**Comment by zevv** [comment]
> This is because that's C code before preprocessing. Simply running -p
> is not sufficient since the `PARAM` statement is defined in `rlstdc.h`
> which is included before `rltypedefs.h` in `readline.h`. 

Of course, but the resulting behaviour is just a bit nasty. I understand
its treesitter messing up, so there is probaby not much nimterop can
do...

**Comment by genotrance** [comment]
I agree, let me see if I can handle it better somehow.

**Comment by genotrance** [comment]
This might be fixed with latest commit to handle broken ASTs. Verified locally but please confirm and close accordingly.

**Comment by zevv** [comment]
Fixed, thanks again!
