### ISSUE TITLE
`nimble develop` should work

### ISSUE THREAD

**Issue by timotheecour** [genotrance/nimterop#62]
[EDIT] still trying to make up my mind whether this is an actual bug or not; maybe the correct answer is for user to set both PATH and NIMBLE_DIR to be consistent; need to think

`nimble develop` in a nimterop clone shd work in isolation (ie not pickup an external `toast` since `toast` is built by this package)

## problem 1
```
export NIMBLE_DIR=$HOME/.nimble_fake4
git clone https://github.com/genotrance/nimterop
cd nimterop
nimble develop
nimble build
nimble test
```

```
   Warning: Using env var NIM_LIB_PREFIX: /Users/timothee/git_clone//nim//Nim/
  Executing task test in /private/tmp/d34/nimterop/nimterop.nimble
nim c -r tests/tnimterop_c.nim
Hint: used config file '/Users/timothee/git_clone/nim/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/Nim/config/config.nims' [Conf]
/private/tmp/d34/nimterop/tests/tnimterop_c.nim(2, 16) Error: cannot open file: nimterop/cimport
stack trace: (most recent call last)
/private/tmp/d34/nimterop/nimterop.nimble(24) testTask
/private/tmp/d34/nimterop/nimterop.nimble(17) execCmd
/Users/timothee/git_clone/nim/Nim/lib/system/nimscript.nim(241) exec
/Users/timothee/git_clone/nim/Nim/lib/system/nimscript.nim(241, 7) Error: unhandled exception: FAILED: nim c -r tests/tnimterop_c.nim
```

problem: `toast` is generated in ./toast and reffered to as `toast` so isn't picked up
(and err msg doesn't tell u that, needs debugging)

## problem 2
if we omit:

export NIMBLE_DIR=$HOME/.nimble_fake4

then if a user has a toast already built in /Users/timothee/.nimble//bin/toast that one will be picked up instead of the one we're building

this leads to hard to diagnose errors

## solution
`nimble test` and other commands shd be smart about how to refer to toast, maybe via an absolute path computed from stuff like:
* getCurrentSource etc

it should "do the right thing" regardless `nimble install` or `nimble develop` is used

## workaround
* `nimble install` to update `/Users/timothee/.nimble//bin/toast` then `nimble develop` again

**Comment by genotrance** [comment]
Nimble relies on user putting `~/.nimble/bin` in the path. We could use `nimble path package` and figure out where `toast` is if needed.
